<?php

return [
    'APP_ADMIN_EMAIL' => null,
    'APP_ADMIN_GOOGLE_LOGIN' => null,
    'APP_ADMIN_GOOGLE_PASS' => null,
    'APP_ADMIN_MAILER_LOGIN' => null,
    'APP_ADMIN_MAILER_PASS' => null,
    'APP_ADMIN_PHONE' => null,
    'APP_EXPO_TOKEN' => null,
    'APP_FIREBASE_FCM_V1_API_KEY' => null,
    'APP_NOVU_API_KEY' => null,
    'APP_NOVU_APP_ID' => null,
    'APP_NOVU_ENV_ID' => null,
    'APP_ONESIGNAL_API_KEY' => null,
    'APP_ONESIGNAL_DEFAULT_RECIPIENT_ID' => null,
    'APP_ONESIGNAL_ID' => null,
    'APP_TELEGRAM_CHAT_ID' => null,
    'APP_TELEGRAM_TOKEN' => null,
    'APP_TO_TEST_EMAIL' => null,
    'APP_TWILIO_FROM' => null,
    'APP_TWILIO_RECOVERY_CODE' => null,
    'APP_TWILIO_SID' => null,
    'APP_TWILIO_TOKEN' => null,
    'CACHE_0_DECRYPTION_KEY' => null,
    'CACHE_1_DECRYPTION_KEY' => null,
    'MERCURE_JWT_SECRET' => null,
    'ONESIGNAL_DSN_AUTH_KEY' => null,
];
