framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
#        app: cache.adapter.redis
#        default_redis_provider: '%env(APP_REDIS_DSN)%'

        # Memcached
#        default_memcached_provider: '%env(APP_MEMCACHED_DSN)%'

#        system: cache.adapter.redis
        #        system: app.cache.fast_and_slow_chain_adapter
        #        system: cache.adapter.memcached

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
#            app.cache.redis:
#                adapters:
#                - 'cache.adapter.redis'
#                default_lifetime: 300 # 300 === 5min

            app.cache.test:
                adapters:
                - 'cache.adapter.array'
                default_lifetime: !php/const PHP_INT_MAX

#            app.cache.memcached:
#                adapters:
#                - 'cache.adapter.memcached'
#                default_lifetime: 300
