cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        route_collection_limit: 0
#        add_locale_pattern: true

        persistence:
            orm:
                enabled: true
#        uri_filter_regexp: '^[/]dynamic'
