endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 300
        margin: 10
        #        logo_path: '%kernel.project_dir%/assets/media/images/film_banner.png'
        encoding: 'UTF-8'
        error_correction_level: 'low'
        round_block_size_mode: 'margin'
        logo_resize_to_width: 150
        logo_punchout_background: true
        validate_result: false
