framework:
    http_client:
        default_options:
            verify_peer: false

when@prod: &when_prod
    framework:
        http_client:
            default_options:
                verify_peer: true
