when@dev: &when_dev
    framework:
        http_client:
            default_options:
                verify_peer: false
                verify_host: true
                timeout: 3
                extra:
                    trace_content: true

framework:
    http_client:
        default_options:
            http_version: '2.0'
        
            verify_peer: true
            verify_host: true
            max_redirects: 10
            extra:
                trace_content: false
    
        scoped_clients:
            this.client:
                base_uri: '%env(DEFAULT_URI)%'