framework:
    rate_limiter:
        limiters:
        
            # Symfony\Component\RateLimiter\RateLimiterFactory $defaultLimiter
            too_rare:
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                #storage_service: app.rate_limiter_storage.default
                
                policy: 'token_bucket'
                limit: 1
                rate:
                    interval: '1 year'
                    amount: 1
            
            short_seconds:
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                #storage_service: app.rate_limiter_storage.default
                
                policy: 'token_bucket'
                limit: 1
                rate:
                    interval: '10 seconds'
                    amount: 1
            
            default:
                #storage_service: app.rate_limiter_storage.default
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                
                policy: 'token_bucket'
                limit: 2
                rate:
                    interval: '30 days'
                    amount: 1
            
            default_request:
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                #storage_service: app.rate_limiter_storage.default
                
                policy: 'token_bucket'
                limit: 1
                rate:
                    interval: '1 minute'
                    amount: 10
                    
            async:
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                #storage_service: app.rate_limiter_storage.default
                
                policy: 'token_bucket'
                limit: 10
                rate:
                    interval: '1 minute'
                    amount: 10
            
            failed:
                #storage_service: app.rate_limiter_storage.default
                
                cache_pool: 'app.cache_adapter.php_files.rate_limiter'
                policy: 'token_bucket'
                limit: 10
                rate:
                    interval: '1 minute'
                    amount: 10