framework:
    http_client:
        default_options:
            http_version: '2.0'
            vars:
                anchor: 'limit-the-number-of-requests'
            verify_peer: true
            verify_host: true
            max_redirects: 10
            timeout: 5
            extra:
                trace_content: false
    
        scoped_clients:
            # default
            client:
                base_uri: '%env(DEFAULT_URI)%'
            
            # one signal
            oneSignal.client:
                base_uri: 'https://onesignal.com'
                auth_bearer: '%env(APP_ONESIGNAL_API_KEY)%'
                headers:
                    Content-Type: 'application/json'
                    Accept: 'application/json'
                
when@dev: &when_dev
    framework:
        http_client:
            default_options:
                verify_peer: false
                verify_host: false
                extra:
                    trace_content: true