# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    profiler:
        enabled: false
        # DO: profiler->enableProfiler instead make it true (globally)
        collect: false

when@dev: &dev
    framework:
        profiler:
            enabled: true
            collect: true
when@test: &test
    framework:
        profiler:
            enabled: true
            collect: true
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file