framework:
    webhook:
        routing:
            mailer_mailgun:
                service: 'mailer.webhook.request_parser.mailgun'
                secret: '%env(APP_WEBHOOK_MAILER_MAILGUN_SECRET)%'

            notifier_twilio:
                service: 'notifier.webhook.request_parser.twilio'
                #secret: '%env(APP_WEBHOOK_SMS_TWILIO_SECRET)%'
                