knpu_oauth2_client:
    clients:
    
        github_main:
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            redirect_route: app_github_login