monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - messenger.email
        - security
        - security.entry_point
        - app.dev

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            messenger.email:
                channels: ["messenger.email"]
                type: 'rotating_file'
                path:  '%kernel.logs_dir%/messenger_email_%kernel.environment%.log'
                level: 'info'
                max_files: 1
            security:
                channels: ["security"]
                type: 'rotating_file'
                path:  '%kernel.logs_dir%/security_%kernel.environment%.log'
                level: 'info'
                max_files: 1
            security.entry_point:
                channels: ["security.entry_point"]
                type: 'rotating_file'
                path:  '%kernel.logs_dir%/security_entry_point_%kernel.environment%.log'
                level: 'info'
                max_files: 1
            app.dev:
                channels: ["app.dev"]
                type: 'rotating_file'
                path:  '%kernel.logs_dir%/app_dev_%kernel.environment%.log'
                level: 'info'
                max_files: 1
                
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
