when@test: &test
    framework:
        notifier:
            texter_transports:
                onesignal:      'null://null'
                twilio:         'null://null'

            chatter_transports:
                telegram:       'null://null'

framework:
    notifier:
        message_bus: messenger.default_bus
        
        texter_transports:
            #twilio:            '%env(TWILIO_DSN)%'
            onesignal:          '%env(ONESIGNAL_DSN)%'
        
        chatter_transports:
            telegram:           '%env(TELEGRAM_DSN)%'

        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent:
            -   'browser'
            #-   'sms/twilio'
            #-   'email'
            #-   'push/onesignal'
            #-   'chat/telegram'
            
            high:
            -   'browser'
            
            medium:
            -   'browser'
            
            low:
            -   'browser'

        admin_recipients:
            -   email:                '%env(APP_ADMIN_EMAIL)%'
                phone:                '%env(APP_ADMIN_PHONE)%'
