framework:
    notifier:
        #message_bus: false
        message_bus: messenger.default_bus
        
        texter_transports:
            onesignal: '%env(ONESIGNAL_DSN)%'
            #twilio: '%env(TWILIO_DSN)%'
        
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'

        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent:
            -   'browser'
            #-   'sms/twilio'
            #-   'email'
            #-   'push/onesignal'
            #-   'chat/telegram'
            
            high:
            -   'browser'
            
            medium:
            -   'browser'
            
            low:
            -   'browser'

        admin_recipients:
        -   email: admin@example.com
