# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    
    ip_whitelist:
    #-   '127.0.0.0/8'
    #-   !php/const Symfony\Component\HttpFoundation\IpUtils::PRIVATE_SUBNETS
    
    # google, email or totp
    #two_factor_provider_decider: 'App\Security\Authenticator\Auth2FA\ProviderDecider\TwoFactorProviderDecider'
    
    #two_factor_condition: app.two_factor_condition
    
    trusted_device:
        enabled: true                 # If the trusted device feature should be enabled
        lifetime: '%app.cookie_lifetime%'
        extend_lifetime: true          # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        #cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax" or "strict"
        #cookie_domain: ".example.com"  # Domain to use when setting the cookie, fallback to the request domain if not set
        #cookie_path: "/"               # Path to use when setting the cookie
    
    backup_codes:
        enabled: true
        
    #email:
        #digits: 3
        #sender_email: '%env(APP_OWNER_EMAIL)%'
        #sender_name: '%env(APP_OWNER_NAME)%'
        #mailer: mailer.mailer
        #code_generator: scheb_two_factor.security.email.code_generator
    
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
        issuer: Localhost
        server_name: Google
        form_renderer: 'App\Security\Authenticator\Auth2FA\DefaultTwoFactorFormRenderer'
        leeway: 5
        
    totp:
        enabled: true
        issuer: Localhost
        server_name: TOTP
        leeway: 0                      # Acceptable time drift in seconds, must be less or equal than the TOTP period
        #parameters:
        #    image: 'https://my-service/img/logo.png'
        #template: 2fa/2fa.thml.twig
        form_renderer: 'App\Security\Authenticator\Auth2FA\DefaultTwoFactorFormRenderer'
    
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - App\Security\AuthenticationToken\FormLoginAuthenticationToken
        - App\Security\AuthenticationToken\GithubAuthenticationToken
