framework:
    default_locale: '%env(APP_LOCALE)%'
    
    enabled_locales: '%app.enabled_locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: '%app.enabled_locales%'
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['ru', 'en']