framework:
    default_locale: '%env(APP_LOCALE)%'
    enabled_locales: '%app.enabled_locales%'
    
    translator:
    
        pseudo_localization:
                enabled: false
                accents: false
                expansion_factor: 1.4
                brackets: false
                parse_html: true
                localizable_html_attributes:
                -   title
                -   form
        default_path: '%kernel.project_dir%/translations'
        fallbacks: '%app.enabled_locales%'
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['ru', 'en']