twig:
    strict_variables: false
    file_name_pattern: '*.twig'
    globals:
        app_text_logo: '%env(APP_TEXT_LOGO)%'
        symfony_version: !php/const Symfony\Component\HttpKernel\Kernel::VERSION

when@test:
    twig:
        strict_variables: true
