# (high priority)
# aliases
# cache
# local
# remote
# (low priority)
ux_icons:
    default_icon_attributes:
        class: 'svg-sm'
        #'aria-label': '' # manually
    
    aliases:
        dots: 'clarity:ellipsis-horizontal-line'
    
    ignore_not_found: true