networks:
    default:
        name: pure_docker_app_net
        driver: bridge

services:

    redis:
        image: redis:latest
        container_name: redis_container
        restart: unless-stopped
        ports:
        - '6379:6379'

    # docker rm app && docker rmi drafts-app && docker compose up
    # for testing
    #    app:
    #        build: .
    #        container_name: app
    #        restart: 'unless-stopped'
    #        volumes:
    #        - './drivers:/app/drivers'

    ###>
    # docker exec -it app_pure_db mysql -p
    #     CREATE DATABASE main;
    ###<
    database:
        image: 'mysql:8.0-debian'
        restart: always
        container_name: app_pure_db
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'

    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        restart: always
        ports:
        - '8080:80'
        environment:
        - PMA_ARBITRARY=1

    ###> symfony/mercure-bundle ###
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        container_name: mercure_container
        environment:
            # Uncomment the following line to disable HTTPS,
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '$MERCURE_PUBLISHER_JWT_KEY'
            MERCURE_SUBSCRIBER_JWT_KEY: '$MERCURE_SUBSCRIBER_JWT_KEY'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://127.0.0.1:8000
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
        #        healthcheck:
        #            test: [ "CMD", "curl", "-f", "https://localhost/healthz" ]
        #            timeout: 5s
        #            retries: 5
        #            start_period: 60s
        volumes:
        - mercure_data:/data
        - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
    ###> symfony/mercure-bundle ###
    mercure_data:
    mercure_config:
###< symfony/mercure-bundle ###
