App\Controller\RgbColor:
    attributes:
        red:
            serialized_name: r_e_d
            groups:
            -   group1
        green:
            serialized_name: g_r_e_e_n
            groups:
            -   group1
        blue:
            serialized_name: b_l_u_e
            groups:
            -   group1
        color:
            max_depth: 1