grin_way_generic_parts_routes_prefixed:
    type:           annotation
    resource:       ../src/Controller
    # don't change prefix
    prefix:         /{_locale<%grin_way_generic_parts.regex_locale%>}/gs/generic-parts
    
grin_way_generic_parts_routes:
    type:           annotation
    resource:       ../src/Controller
    # don't change prefix
    prefix:         /gs/generic-parts