services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        
        bind:
            ###> KERNEL ###
            $projectDir: '%kernel.project_dir%'
            $absCacheDir: '%kernel.cache_dir%'
            $debug: '%kernel.debug%'
            ###< KERNEL ###

            
            ###> SERVICES ###
            $t:                 '@Symfony\Contracts\Translation\TranslatorInterface'
            ###< SERVICES ###

            
            ###> URL ###
            $appUrl: '%env(APP_URL)%'
            ###< URL ###
            
            
            ###> LANG ###
            $appEnabledLocales: '%app.enabled_locales%'
            ###< LANG ###

            
            ###> ASCII ###
            $emojiSlugger: '@app.slugger_with_emoji'
            ###< ASCII ###
            

            ###> grinway ###
            $ru12Carbon:  '@app.ru_12_carbon'
            $enUtcCarbon: '@app.en_utc_carbon'
            $faker:       '@grin_way_service.faker'
            ###< grinway ###


            ###> PARAMS ###
            $kernelProjectDir:  '%kernel.project_dir%'
            $adminEmail:        '%env(APP_ADMIN_EMAIL)%'
            $adminPhone:        '%env(APP_ADMIN_PHONE)%'
            ###< PARAMS ###


            ###> MESSENGER ###
            $adminSendEmailMessage: '@app.messenger.notifier.admin_send_email'

            $get: '@grin_way_web_app.messenger.query'

            $messengerServiceLocator: '@app.messenger.service_locator'
            ###< MESSENGER ###


            ###> PROMOCODE ###
            $promocodes: !tagged_locator
                tag: 'app.promocode'
            ###< PROMOCODE ###


            #//TODO (NewClosureDefinitionWithTagPass) USAGE:
            ###> HASH ###
            $callableHashLocator: !tagged_locator
                tag: !php/const 'App\Type\Hash\HashType::TAG'
                index_by: index
            ###< HASH ###

            
            ###> PATHS ###
            $absPublicDir: '%app.abs_public_dir%'
            $absCustomConfigParametersDir: '%kernel.project_dir%/config/services_yaml/custom/parameters'
            $absConfigParametersDir: '%kernel.project_dir%/config/services_yaml/parameters'
            ###< PATHS ###

    ###> AUTOLOAD SERVICES BY NAMESPACE AND RESOURCE
    App\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Attribute/'
            - '../../src/Entity/'
            - '../../src/Exception/'
            - '../../src/Contract/'
            - '../../src/EventSubscriber/'
            - '../../src/Kernel.php'
            - '../../src/Service/Anonymous/'
            - '../../src/Service/PureStatic/'
            - '../../src/Panther/'
            - '../../src/Test/'
            - '../../src/Resources/'