App\Entity\Media\Media:

    constraints:
    # DOESN'T WORK, that's not a constraint
    #-   GroupSequenceProvider: 'App\Validation\GroupProvider\Entity\MediaGroupProvider'
    
    properties:
        filepath:
        -   Expression:
                expression: "false" #false
                groups:
                -   '_1'
        fileOriginalName:
        -   Expression:
                expression: "false" #false
                groups:
                -   '_2'
        fileToken:
        -   Expression:
                expression: "false" #false
                groups:
                -   '_3'
        createdAt:
        -   Expression:
                expression: "false" #false
                groups:
                -   '_4'
    
    getters: