App\Entity\Product\Product:

    #group_sequence:
    #-   regex
    
    group_sequence_provider: null
    #group_sequence_provider: true
    group_sequence_provider: App\Validation\GroupProvider\Entity\ProductGroupProvider
    
    constraints:
    -   Cascade:
    #-   DisableAutoMapping:
    #-   EnableAutoMapping:
    
    properties:
        description:
        -   App\Validation\Constraint\IsRegex:
                payload:
                    level: !php/const App\Type\Note\NoteType::ERROR
        
    getters: