App\Entity\User:

    constraints:
    #-   GroupSequenceProvider: 'App\Validation\GroupProvider\Entity\UserGroupProvider'
    -   Cascade:
    -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
            -   email
    
    properties:
        email:
        -   Type:
                type: 'string'
                groups:
                -   login
                -   register
        -   NotBlank:
                groups:
                -   login
                -   register
        # хоть пароль и в регистрационной форме, он mapped=false,
        # ограничения здесь нельзя применять при register
        password:
        -   Type:
                type: 'string'
                groups:
                -   login
        -   Length:
                max: 255
                groups:
                -   login
        -   NotBlank:
                message: 'Пустой пароль!'
                groups:
                -   login
        passport:
        -   Type:
                type: 'App\Entity\UserPassport'
                groups:
                -   register
        switchUserAble:
        -   Type:
                type: 'boolean'
                groups:
                -   register
        
    getters: