App\Entity\User:

    constraints:
    -   Cascade:
    -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
            -   email
    
    properties:
        
    getters: