parameters:

    app.fixture.users: 15
    app.fixture.product.toy: 5
    app.fixture.product.food: 5
    app.fixture.product.furniture: 5
    app.fixture.product.task: 5
    app.fixture.product.task_food_topic: 2
    app.fixture.product.image: 5
    app.fixture.product.avatar: 5