parameters:
    env(APP_MAILER_HEADER_FROM_TITLE): '[Мастер] %env(APP_TITLE)%'
    env(APP_MAILER_HEADER_FROM): '%env(APP_MAILER_HEADER_FROM_TITLE)% <%env(APP_ADMIN_EMAIL)%>'
    env(APP_MAILER_HEADER_SUBJECT): '%env(APP_TITLE)%'
    #env(MAILER_DSN): 'smtp://%env(APP_ADMIN_GOOGLE_LOGIN)%:%env(APP_ADMIN_GOOGLE_PASS)%@smtp.gmail.com:25?verify_peer=0&local_domain=woodenalex.ru&restart_threshold=10&restart_threshold_sleep=1&max_per_second=2'
    #failover
    #&peer_fingerprint=
    env(MAILER_DEFAULT_TRANSPORT): 'smtp://%env(APP_ADMIN_MAILER_LOGIN)%:%env(APP_ADMIN_MAILER_PASS)%@smtp.woodenalex.ru:25?verify_peer=0&local_domain=woodenalex.ru&restart_threshold=10&restart_threshold_sleep=1&max_per_second=2&auto_tls=false'
    env(MAILER_GOOGLE_TRANSPORT): 'smtp://%env(APP_ADMIN_GOOGLE_LOGIN)%:%env(APP_ADMIN_GOOGLE_PASS)%@smtp.gmail.com:25?verify_peer=0&local_domain=woodenalex.ru&restart_threshold=10&restart_threshold_sleep=1&max_per_second=2&auto_tls=false'
    #env(MAILER_DSN): 'roundrobin(%env(MAILER_DEFAULT_TRANSPORT)% %env(MAILER_GOOGLE_TRANSPORT)%)'
    #env(MAILER_DSN): 'failover(%env(MAILER_DEFAULT_TRANSPORT)% %env(MAILER_GOOGLE_TRANSPORT)%)'
    env(MAILER_DSN): '%env(MAILER_DEFAULT_TRANSPORT)%'
    #env(MAILER_DSN): '%env(MAILER_GOOGLE_TRANSPORT)%'