parameters:
    #env(TWILIO_DSN): 'twilio://%env(APP_TWILIO_SID)%:%env(APP_TWILIO_TOKEN)%@default?from=FROM'    
    
    env(TELEGRAM_DSN): 'telegram://%env(APP_TELEGRAM_TOKEN)%@default?channel=%env(APP_TELEGRAM_CHAT_ID)%'
    
    env(ONESIGNAL_DSN): 'onesignal://%env(APP_ONESIGNAL_ID)%:%env(APP_ONESIGNAL_API_KEY)%@default?defaultRecipientId=%env(APP_ONESIGNAL_DEFAULT_RECIPIENT_ID)%'
    