parameters:
    
    env(APP_TELEGRAM_DSN): 'telegram://%env(APP_TELEGRAM_TOKEN)%@default?channel=%env(APP_TELEGRAM_CHAT_ID)%'
    

    # symfony/notifier ^6 copability only
    #env(APP_NOVU_DSN): 'novu://%env(APP_NOVU_API_KEY)%@default'

    # too difficult, new android app?!
    #env(APP_EXPO_DSN):     'expo://%env(APP_EXPO_TOKEN)%@default'
    
    env(APP_ONESIGNAL_DSN): 'onesignal://%env(APP_ONESIGNAL_ID)%:%env(APP_ONESIGNAL_API_KEY)%@default?defaultRecipientId=%env(APP_ONESIGNAL_DEFAULT_RECIPIENT_ID)%'
    
    
    #env(APP_TWILIO_DSN): 'twilio://%env(APP_TWILIO_SID)%:%env(APP_TWILIO_TOKEN)%@default?from=FROM'    

    