when@test: &when_test
    imports:
        -   resource: 'services_yaml/test/services/'
        -   resource: 'services_yaml/test/parameters/'

###> imports are loaded first (imports not override existing services) ###
imports:
    # (last)
    -   resource: 'services_yaml/resource_services.yaml'    #
    -   resource: 'services_yaml/services/'                 # 
    -   resource: 'services_yaml/parameters/'               #
    -   resource: 'services_yaml/custom/'                   #
    # (first)

###> then services.yaml (what below overrides imports) ###
###>... it's better to use only imports