services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            ###> EMAIL ###
            $appTestEmail: '%env(APP_TEST_EMAIL)%'
            ###< EMAIL ###

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
