twig:

    paths:
        '%kernel.project_dir%/vendor/grinway/generic-parts-bundle':           GrinWayGenericPartsBundle

    globals:
        grin_way_generic_parts:
            timezone_session_name:                      '%grin_way_generic_parts.timezone_session_name%'