services:
    
    _defaults:
        autowire: true
        autoconfigure: true

    App\EventSubscriber\EasyAdmin\Entity\AfterCrudActionEventSubscriber:
        class: App\EventSubscriber\EasyAdmin\Entity\AfterCrudActionEventSubscriber
        tags:
        -   name: 'kernel.event_subscriber'