services:

    _defaults:
        autowire: true
        autoconfigure: true
    
    
    Symfony\Component\Cache\Adapter\PhpFilesAdapter:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        arguments:
            $namespace: cache_php_files
            $defaultLifetime: 30
            $directory: '%kernel.cache_dir%'
            $appendOnly: false

    app.cache_adapter.php_files: '@Symfony\Component\Cache\Adapter\PhpFilesAdapter'


    Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter:
        class: 'Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter'
        arguments:
            $namespace: cache_filesystem
            $defaultLifetime: 30
            $directory: '%kernel.cache_dir%'
            $marshaller: null
            
    app.cache_adapter.filesystem_tag_aware: '@Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter'


    app.service.cache_util:
        class: App\Service\CacheUtil
        arguments:
            $container: !service_locator
                
                php_files: '@app.cache_adapter.php_files'
                
                doctrine: !service
                    class: 'Symfony\Component\Cache\Adapter\DoctrineDbalAdapter'
                    arguments:
                        $connOrDsn: '%env(DATABASE_URL)%'
                        $namespace: ''
                        $defaultLifetime: 30
                        $options: []
                        $marshaller: null
                
                array: !service
                    class: 'Symfony\Component\Cache\Adapter\ArrayAdapter'
                    arguments:
                        $defaultLifetime: 0
                        $storeSerialized: true
                        $maxLifetime: 0
                        $maxItems: 0
                
                filesystem_tag_aware: '@app.cache_adapter.filesystem_tag_aware'
                
    App\Service\CacheUtil: '@app.service.cache_util'
        