services:
    
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\Imports\CheckBindWithImports:
        class: App\Service\Imports\CheckBindWithImports
        arguments:
            $faker: '@grin_way_service.faker'