services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\EntityUserProvider
        arguments:
            $class: App\Entity\User
            $properties:
                github: gitHub.id
        
    ###> DECORATOR
    app.hwi_oauth.user.provider.entity:
        decorates: hwi_oauth.user.provider.entity
        class: App\Security\OAuth\HWIOAuthBundle\Provider\EntityUserProvider
        arguments:
            $inner: '@.inner'