services:

    _defaults:
        autowire: true
        autoconfigure: true

    #Monolog\Processor\IntrospectionProcessor:
    #    tags:
    #    -   name: monolog.processor
    #        handler: 'app.mail'