services:

    _defaults:
        autowire: true
        autoconfigure: true
    
    # Cache Encryption
    #Symfony\Component\Cache\Marshaller\SodiumMarshaller:
    #    decorates: cache.default_marshaller
    #    arguments:
    #    -
    #        -   '%env(base64:CACHE_1_DECRYPTION_KEY)%'
    #        -   '%env(base64:CACHE_0_DECRYPTION_KEY)%'
    #    -   '@.inner'
