# https://symfony.com/doc/current/logging/processors.html#registering-processors-per-handler
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Bridge\Monolog\Processor\TokenProcessor:
        class: Symfony\Bridge\Monolog\Processor\TokenProcessor
        tags:
        -   name: 'monolog.processor'
            handler: 'app.mail.groupped'
        
    Symfony\Bridge\Monolog\Processor\SwitchUserTokenProcessor:
        class: Symfony\Bridge\Monolog\Processor\SwitchUserTokenProcessor
        tags:
        -   name: 'monolog.processor'
            handler: 'app.mail.groupped'
        
    Symfony\Bridge\Monolog\Processor\WebProcessor:
        class: Symfony\Bridge\Monolog\Processor\WebProcessor
        tags:
        -   name: 'monolog.processor'
            handler: 'app.mail.groupped'
        
    Symfony\Bridge\Monolog\Processor\RouteProcessor:
        class: Symfony\Bridge\Monolog\Processor\RouteProcessor
        tags:
        -   name: 'monolog.processor'
            handler: 'app.mail.groupped'
        
    Symfony\Bridge\Monolog\Processor\ConsoleCommandProcessor:
        class: Symfony\Bridge\Monolog\Processor\ConsoleCommandProcessor
        tags:
        -   name: 'monolog.processor'
            handler: 'app.mail.groupped'