services:

    _defaults:
        autowire: true
        autoconfigure: true

    notifier.flash_message_importance_mapper:
        class: App\Notification\BrowserNotification\AppFlashMessageImportanceMapper