services:

    _defaults:
        autowire: true
        autoconfigure: true

    #Symfony\Component\PropertyAccess\PropertyAccessorInterface:
    #    class: Symfony\Component\PropertyAccess\PropertyAccessor
    #    tags:
    #    -   name: container.hot_path
    