services:

    app.inline_reader:
        class: App\Service\InlineReader
    
    app.download_reader:
        class: App\Service\DownloadReader
    
    #...
    
    # DEFAULT (based on the configuration: '../parameters/reader.yaml')
    app.reader:
        tags:
        -   name:   'auto_alias'
            format: 'app.%app.render_strategy%_reader'