services:
    _defaults:
        bind:
            $kernelProjectDir:  '%kernel.project_dir%'

    App\Service\Router\AttributeRouterReader:
        class: App\Service\Router\AttributeRouterReader
        tags:
        -   routing.loader
        
    decorated_attribute_router_reader:
        stack:
        -   class: App\Service\Router\Decorator\AttributeRouterReader
            decoration_on_invalid: null
            arguments:
            -   '%kernel.project_dir%'
            -   '%env(APP_ENV)%'
            -   '@?.inner'
        -   class: App\Service\Router\AttributeRouterReader
            arguments:
            -   '%kernel.project_dir%'
            -   '%env(APP_ENV)%'
    
    app.router.expression_language_provider:
        class: App\Router\ExpressionLanguage\ExpressionLanguageProvider\RouterExpressionLanguageProviderDecorator
        decorates: router.expression_language_provider
        arguments:
            $inner: '@.inner'
    
    ###> request_matcher ###
    app.request_matcher.localhost:
        class: 'App\Security\RequestMatcher\IpRangeRequestMatcher'
        arguments:
            $minIdx0: 127
            $maxIdx0: 127
            
            $minIdx1: 0
            $maxIdx1: 255
            
            $minIdx2: 0
            $maxIdx2: 255
            
            $minIdx3: 1
            $maxIdx3: 254

    app.request_matcher.localhost_home:
        class: Symfony\Component\HttpFoundation\ChainRequestMatcher
        arguments:
        -
            -   !service
                    class: 'App\Security\RequestMatcher\UrlRequestMatcher'
            -   '@app.request_matcher.localhost'
    ###< request_matcher ###