services:
    
    _defaults:
        autowire: true
        autoconfigure: true

    Vich\UploaderBundle\Naming\SlugNamer:
        class: Vich\UploaderBundle\Naming\SlugNamer
        public: true
        arguments:
            $transliterator: '@Vich\UploaderBundle\Util\Transliterator'
            $service: '@App\Repository\MediaRepository'
            $method: findOneByPath

    App\Service\Naming\SlugNamer:
        public: true
        class: App\Service\Naming\SlugNamer
        arguments:
            $slugger: '@slugger'